// Ported from diuf.sudoku.SolvingTechnique. In-scope members only, in Java
// declaration order. String enum so a value equals its Java toString() display
// name.
export enum SolvingTechnique {
  HiddenSingle = 'Hidden Single',
  DirectPointing = 'Direct Pointing',
  DirectHiddenPair = 'Direct Hidden Pair',
  NakedSingle = 'Naked Single',
  DirectHiddenTriplet = 'Direct Hidden Triplet',
  PointingClaiming = 'Pointing & Claiming',
  NakedPair = 'Naked Pair',
  XWing = 'X-Wing',
  HiddenPair = 'Hidden Pair',
  NakedTriplet = 'Naked Triplet',
  Swordfish = 'Swordfish',
  HiddenTriplet = 'Hidden Triplet',
  TurbotFish = 'Scraper, Kite, Turbot',
  XYWing = 'XY-Wing',
  XYZWing = 'XYZ-Wing',
  WXYZWing = 'WXYZ-Wing',
  UniqueLoop = 'Unique Rectangle / Loop',
  NakedQuad = 'Naked Quad',
  Jellyfish = 'Jellyfish',
  HiddenQuad = 'Hidden Quad',
  ThreeStrongLinks = '3 Strong-linked Fishes',
  VWXYZWing = 'VWXYZ-Wing',
  BivalueUniversalGrave = 'Bivalue Universal Grave',
  FourStrongLinks = '4 Strong-Linked Fishes',
  AlignedPairExclusion = 'Aligned Pair Exclusion',
  FiveStrongLinks = '5 Strong-Linked Fishes',
  SixStrongLinks = '6 Strong-Linked Fishes',
  UVWXYZWing = 'UVWXYZ-Wing',
  ForcingChainCycle = 'Forcing Chains & Cycles',
  TUVWXYZWing = 'TUVWXYZ-Wing',
  AlignedTripletExclusion = 'Aligned Triplet Exclusion',
  NishioForcingChain = 'Nishio Forcing Chains',
  MultipleForcingChain = 'Multiple Forcing Chains',
  DynamicForcingChain = 'Dynamic Forcing Chains',
  DynamicForcingChainPlus = 'Dynamic Forcing Chains (+)',
  NestedForcingChain = 'Nested Forcing Chains',
}
