import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..');
const SRC = join(REPO, 'SukakuExplainer', 'diuf', 'sudoku', 'solver');
const OUT = join(REPO, 'src', 'templates');

// Templates out of scope for the vanilla-Sudoku port (see step-006).
const SKIP = new Set([
  'forcingCellNC.html',
  'lockedNC.html',
  'VLocking.html',
  'NakedSetGenHint.html',
  'UnderConstruction.html',
]);

const SENT = {
  h: 'H',
  eh: 'EH',
  p: 'P',
  br: 'BR',
  li: 'LI',
  ul: 'UL',
  eul: 'EUL',
} as const;

// HtmlLoader.formatColors maps the custom color tags to Java Swing colors; the
// port keeps those roles as span color names (see step-006 conversion rules).
const COLOR: Record<string, string> = {
  c: 'cyan', // #00AAAA
  g: 'green', // #009000
  r: 'red',
  o: 'orange', // #E08000
  b1: 'blue', // #0000A0
  b2: 'darkgreen', // #005000
};

function convert(html: string): string {
  let s = html;

  // Drop document wrappers.
  s = s.replace(/<\/?(?:html|body)>/gi, '');

  // Color tags: order matters, b1/b2 before b so bold conversion cannot eat them.
  for (const tag of ['b1', 'b2', 'c', 'g', 'r', 'o']) {
    s = s.replace(new RegExp(`<${tag}>`, 'g'), `<span color="${COLOR[tag]}">`);
    s = s.replace(new RegExp(`</${tag}>`, 'g'), '</span>');
  }

  // Inline emphasis. <u> stays inline HTML.
  s = s.replace(/<b>/g, '**').replace(/<\/b>/g, '**');
  s = s.replace(/<i>/g, '*').replace(/<\/i>/g, '*');

  // Structural tags to sentinels.
  s = s.replace(/<h2>/gi, SENT.h).replace(/<\/h2>/gi, SENT.eh);
  s = s.replace(/<\/?p>/gi, SENT.p);
  s = s.replace(/<ul>/gi, SENT.ul).replace(/<\/ul>/gi, SENT.eul);
  s = s.replace(/<\/?li>/gi, SENT.li);
  s = s.replace(/<br\s*\/?>/gi, SENT.br);

  // Decode the HTML entities that appear in the templates.
  s = s
    .replace(/&gt;/g, '>')
    .replace(/&lt;/g, '<')
    .replace(/&amp;/g, '&')
    .replace(/&nbsp;/g, ' ');

  // Collapse all whitespace runs to single spaces (HTML rendering semantics).
  s = s.replace(/\s+/g, ' ');

  // Expand sentinels, trimming spaces around block-level breaks.
  s = s.replace(/ *BR */g, '  \n');
  s = s.replace(/ *LI */g, '\n- ');
  s = s.replace(/ *UL */g, '\n');
  s = s.replace(/ *EUL */g, '\n\n');
  s = s.replace(/ *H */g, '## ');
  s = s.replace(/ *EH */g, '\n\n');
  s = s.replace(/ *P */g, '\n\n');

  // Collapse extra blank lines and trim.
  s = s.replace(/\n{3,}/g, '\n\n');
  return s.trim();
}

function exportName(file: string): string {
  return file.replace(/\.html$/, '').replace(/[^A-Za-z0-9_]/g, '');
}

function buildModule(dir: string): { code: string; count: number } {
  const files = readdirSync(dir)
    .filter((f) => f.endsWith('.html') && !SKIP.has(f))
    .sort();
  const lines = ['// generated by scripts/convert-templates.ts, do not edit by hand', ''];
  for (const file of files) {
    const md = convert(readFileSync(join(dir, file), 'latin1'));
    lines.push(`export const ${exportName(file)} = ${JSON.stringify(md)};`);
  }
  return { code: lines.join('\n') + '\n', count: files.length };
}

const modules: Array<[string, string]> = [
  ['rules.ts', SRC],
  ['rulesChaining.ts', join(SRC, 'rules', 'chaining')],
  ['rulesUnique.ts', join(SRC, 'rules', 'unique')],
  ['checks.ts', join(SRC, 'checks')],
];

// rules.ts is the non-recursive rules directory only.
modules[0][1] = join(SRC, 'rules');

let total = 0;
for (const [outFile, dir] of modules) {
  const { code, count } = buildModule(dir);
  writeFileSync(join(OUT, outFile), code);
  total += count;
  console.log(`${outFile}: ${count} templates`);
}
console.log(`total: ${total} templates`);
